from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel
from PyQt5.Qt import pyqtSignal
import sys
from PyQt5 import QtCore, QtGui, QtWidgets

class ClickedLabel(QLabel):
    clicked = pyqtSignal()

    def mouseReleaseEvent(self, e):
        super().mouseReleaseEvent(e)

        self.clicked.emit()

class AuthorizationUI(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(34, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        Widget.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        Widget.setFont(font)
        self.AuthorizationFrame = QtWidgets.QFrame(Widget)
        self.AuthorizationFrame.setEnabled(True)
        self.AuthorizationFrame.setGeometry(QtCore.QRect(250, 100, 301, 261))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(71, 75, 79))
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        self.AuthorizationFrame.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.AuthorizationFrame.setFont(font)
        self.AuthorizationFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.AuthorizationFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.AuthorizationFrame.setLineWidth(300)
        self.AuthorizationFrame.setMidLineWidth(0)
        self.AuthorizationFrame.setObjectName("AuthorizationFrame")
        self.AuthrroizationLabel = QtWidgets.QLabel(self.AuthorizationFrame)
        self.AuthrroizationLabel.setGeometry(QtCore.QRect(80, 10, 141, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(97, 137, 47))
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        self.AuthrroizationLabel.setPalette(palette)
        self.AuthrroizationLabel.setObjectName("AuthrroizationLabel")
        self.LoginLabel = QtWidgets.QLabel(self.AuthorizationFrame)
        self.LoginLabel.setGeometry(QtCore.QRect(10, 60, 71, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(97, 137, 47))
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 137, 47))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        self.LoginLabel.setPalette(palette)
        self.LoginLabel.setObjectName("LoginLabel")
        self.PasswordLabel = QtWidgets.QLabel(self.AuthorizationFrame)
        self.PasswordLabel.setGeometry(QtCore.QRect(10, 90, 91, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(97, 137, 47))
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 137, 47))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        self.PasswordLabel.setPalette(palette)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.SaveMeGAlochka = QtWidgets.QRadioButton(self.AuthorizationFrame)
        self.SaveMeGAlochka.setGeometry(QtCore.QRect(20, 130, 181, 22))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(97, 137, 47))
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 137, 47))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        self.SaveMeGAlochka.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.SaveMeGAlochka.setFont(font)
        self.SaveMeGAlochka.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SaveMeGAlochka.setObjectName("SaveMeGAlochka")
        self.EnterButton = QtWidgets.QPushButton(self.AuthorizationFrame)
        self.EnterButton.setGeometry(QtCore.QRect(90, 160, 131, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        self.EnterButton.setPalette(palette)
        self.EnterButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.EnterButton.setObjectName("EnterButton")
        self.RegisterButtonLabel = ClickedLabel(self.AuthorizationFrame)
        self.RegisterButtonLabel.setGeometry(QtCore.QRect(20, 190, 231, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(97, 137, 47))
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        self.RegisterButtonLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(False)
        font.setUnderline(True)
        self.RegisterButtonLabel.setFont(font)
        self.RegisterButtonLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RegisterButtonLabel.setObjectName("RegisterButtonLabel")
        self.ForgetPasswordLabelButton = ClickedLabel(self.AuthorizationFrame)
        self.ForgetPasswordLabelButton.setGeometry(QtCore.QRect(20, 220, 101, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(97, 137, 47))
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        self.ForgetPasswordLabelButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(False)
        font.setUnderline(True)
        self.ForgetPasswordLabelButton.setFont(font)
        self.ForgetPasswordLabelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ForgetPasswordLabelButton.setObjectName("ForgetPasswordLabelButton")
        self.LoginEnterField = QtWidgets.QLineEdit(self.AuthorizationFrame)
        self.LoginEnterField.setGeometry(QtCore.QRect(100, 60, 151, 24))
        self.LoginEnterField.setAutoFillBackground(False)
        self.LoginEnterField.setObjectName("LoginEnterField")
        self.PasswrodEnterField = QtWidgets.QLineEdit(self.AuthorizationFrame)
        self.PasswrodEnterField.setGeometry(QtCore.QRect(100, 100, 151, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        self.PasswrodEnterField.setPalette(palette)
        self.PasswrodEnterField.setObjectName("PasswrodEnterField")
        self.AuthrroizationLabel.raise_()
        self.LoginLabel.raise_()
        self.PasswordLabel.raise_()
        self.SaveMeGAlochka.raise_()
        self.RegisterButtonLabel.raise_()
        self.ForgetPasswordLabelButton.raise_()
        self.LoginEnterField.raise_()
        self.PasswrodEnterField.raise_()
        self.EnterButton.raise_()
        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "MemoryGame"))
        self.AuthrroizationLabel.setText(_translate("Widget", "Авторизация"))
        self.LoginLabel.setText(_translate("Widget", "Логин"))
        self.PasswordLabel.setText(_translate("Widget", "Пароль"))
        self.SaveMeGAlochka.setText(_translate("Widget", "Запомнить меня?"))
        self.EnterButton.setText(_translate("Widget", "Войти"))
        self.RegisterButtonLabel.setText(_translate("Widget", "У меня нет аккаунта."))
        self.ForgetPasswordLabelButton.setText(_translate("Widget", "Забыли пароль?"))


class MainMenuUI(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(34, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        Widget.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        Widget.setFont(font)
        self.AuthorizationFrame = QtWidgets.QFrame(Widget)
        self.AuthorizationFrame.setEnabled(True)
        self.AuthorizationFrame.setGeometry(QtCore.QRect(250, 100, 301, 401))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(71, 75, 79))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        self.AuthorizationFrame.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(False)
        self.AuthorizationFrame.setFont(font)
        self.AuthorizationFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.AuthorizationFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.AuthorizationFrame.setLineWidth(300)
        self.AuthorizationFrame.setMidLineWidth(0)
        self.AuthorizationFrame.setObjectName("AuthorizationFrame")
        self.AuthrroizationLabel = QtWidgets.QLabel(self.AuthorizationFrame)
        self.AuthrroizationLabel.setGeometry(QtCore.QRect(0, 0, 301, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(97, 137, 47))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.AuthrroizationLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        self.AuthrroizationLabel.setFont(font)
        self.AuthrroizationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AuthrroizationLabel.setObjectName("AuthrroizationLabel")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.AuthorizationFrame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 301, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ButtonStart = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ButtonStart.setObjectName("ButtonStart")
        self.verticalLayout.addWidget(self.ButtonStart)
        self.ButtonResults = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ButtonResults.setObjectName("ButtonResults")
        self.verticalLayout.addWidget(self.ButtonResults)
        self.ButtonSettings = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ButtonSettings.setObjectName("ButtonSettings")
        self.verticalLayout.addWidget(self.ButtonSettings)
        self.ButtonExit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ButtonExit.setObjectName("ButtonExit")
        self.verticalLayout.addWidget(self.ButtonExit)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "MemoryGame"))
        self.AuthrroizationLabel.setText(_translate("Widget", "Главное меню"))
        self.ButtonStart.setText(_translate("Widget", "Игра памяти"))
        self.ButtonResults.setText(_translate("Widget", "Результаты"))
        self.ButtonSettings.setText(_translate("Widget", "Настройки"))
        self.ButtonExit.setText(_translate("Widget", "Выход"))

class Register1UI(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(34, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        Widget.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        Widget.setFont(font)
        self.AuthorizationFrame = QtWidgets.QFrame(Widget)
        self.AuthorizationFrame.setEnabled(True)
        self.AuthorizationFrame.setGeometry(QtCore.QRect(250, 100, 301, 401))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(71, 75, 79))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        self.AuthorizationFrame.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(False)
        self.AuthorizationFrame.setFont(font)
        self.AuthorizationFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.AuthorizationFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.AuthorizationFrame.setLineWidth(300)
        self.AuthorizationFrame.setMidLineWidth(0)
        self.AuthorizationFrame.setObjectName("AuthorizationFrame")
        self.AuthrroizationLabel = QtWidgets.QLabel(self.AuthorizationFrame)
        self.AuthrroizationLabel.setGeometry(QtCore.QRect(0, 0, 301, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(97, 137, 47))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.AuthrroizationLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        self.AuthrroizationLabel.setFont(font)
        self.AuthrroizationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AuthrroizationLabel.setObjectName("AuthrroizationLabel")
        self.formLayoutWidget = QtWidgets.QWidget(self.AuthorizationFrame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 60, 301, 301))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelFamily = QtWidgets.QLabel(self.formLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(253, 253, 253))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.labelFamily.setPalette(palette)
        self.labelFamily.setObjectName("labelFamily")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelFamily)
        self.familyField = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.familyField.setObjectName("familyField")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.familyField)
        self.labelName = QtWidgets.QLabel(self.formLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(229, 242, 255))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.labelName.setPalette(palette)
        self.labelName.setObjectName("labelName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelName)
        self.NameField = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.NameField.setObjectName("NameField")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.NameField)
        self.labelGroup = QtWidgets.QLabel(self.formLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(229, 242, 255))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.labelGroup.setPalette(palette)
        self.labelGroup.setObjectName("labelGroup")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelGroup)
        self.GroupField = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.GroupField.setObjectName("GroupField")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.GroupField)
        self.labelLogin = QtWidgets.QLabel(self.formLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(229, 242, 255))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.labelLogin.setPalette(palette)
        self.labelLogin.setObjectName("labelLogin")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelLogin)
        self.LoginField = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LoginField.setObjectName("LoginField")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LoginField)
        self.labelPassword = QtWidgets.QLabel(self.formLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(229, 242, 255))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.labelPassword.setPalette(palette)
        self.labelPassword.setObjectName("labelPassword")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelPassword)
        self.PasswordField = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.PasswordField.setObjectName("PasswordField")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.PasswordField)
        self.NextButton = QtWidgets.QPushButton(self.AuthorizationFrame)
        self.NextButton.setGeometry(QtCore.QRect(50, 340, 193, 40))
        self.NextButton.setObjectName("NextButton")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "MemoryGame"))
        self.AuthrroizationLabel.setText(_translate("Widget", "Регистрация"))
        self.labelFamily.setText(_translate("Widget", "Фамилия"))
        self.labelName.setText(_translate("Widget", "Имя"))
        self.labelGroup.setText(_translate("Widget", "Группа"))
        self.labelLogin.setText(_translate("Widget", "Логин"))
        self.labelPassword.setText(_translate("Widget", "Пароль"))
        self.NextButton.setText(_translate("Widget", "Далее"))

class Register2UI(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(34, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        Widget.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        Widget.setFont(font)
        self.AuthorizationFrame = QtWidgets.QFrame(Widget)
        self.AuthorizationFrame.setEnabled(True)
        self.AuthorizationFrame.setGeometry(QtCore.QRect(250, 100, 301, 341))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(71, 75, 79))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        self.AuthorizationFrame.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(False)
        self.AuthorizationFrame.setFont(font)
        self.AuthorizationFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.AuthorizationFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.AuthorizationFrame.setLineWidth(300)
        self.AuthorizationFrame.setMidLineWidth(0)
        self.AuthorizationFrame.setObjectName("AuthorizationFrame")
        self.AuthrroizationLabel = QtWidgets.QLabel(self.AuthorizationFrame)
        self.AuthrroizationLabel.setGeometry(QtCore.QRect(0, 10, 301, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(97, 137, 47))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.AuthrroizationLabel.setPalette(palette)
        self.AuthrroizationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AuthrroizationLabel.setObjectName("AuthrroizationLabel")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.AuthorizationFrame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 301, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MotherLAbel = QtWidgets.QLabel(self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(229, 242, 255))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.MotherLAbel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.MotherLAbel.setFont(font)
        self.MotherLAbel.setObjectName("MotherLAbel")
        self.verticalLayout.addWidget(self.MotherLAbel)
        self.MotherField = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.MotherField.setObjectName("MotherField")
        self.verticalLayout.addWidget(self.MotherField)
        self.PetLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(229, 242, 255))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.PetLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.PetLabel.setFont(font)
        self.PetLabel.setObjectName("PetLabel")
        self.verticalLayout.addWidget(self.PetLabel)
        self.PetField = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.PetField.setObjectName("PetField")
        self.verticalLayout.addWidget(self.PetField)
        self.CityLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(229, 242, 255))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.CityLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.CityLabel.setFont(font)
        self.CityLabel.setObjectName("CityLabel")
        self.verticalLayout.addWidget(self.CityLabel)
        self.CityField = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.CityField.setObjectName("CityField")
        self.verticalLayout.addWidget(self.CityField)
        self.registerButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.registerButton.setObjectName("registerButton")
        self.verticalLayout.addWidget(self.registerButton)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "MemoryGame"))
        self.AuthrroizationLabel.setText(_translate("Widget", "Секретные вопросы"))
        self.MotherLAbel.setText(_translate("Widget", "Девичья фамилия вашей матери:"))
        self.PetLabel.setText(_translate("Widget", "Имя первого домашнего питомца:"))
        self.CityLabel.setText(_translate("Widget", "Город, где родился:"))
        self.registerButton.setText(_translate("Widget", "Завершить"))

class ForgetPasswordUI(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(34, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        Widget.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        Widget.setFont(font)
        self.AuthorizationFrame = QtWidgets.QFrame(Widget)
        self.AuthorizationFrame.setEnabled(True)
        self.AuthorizationFrame.setGeometry(QtCore.QRect(250, 100, 301, 221))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(71, 75, 79))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        self.AuthorizationFrame.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(False)
        self.AuthorizationFrame.setFont(font)
        self.AuthorizationFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.AuthorizationFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.AuthorizationFrame.setLineWidth(300)
        self.AuthorizationFrame.setMidLineWidth(0)
        self.AuthorizationFrame.setObjectName("AuthorizationFrame")
        self.AuthrroizationLabel = QtWidgets.QLabel(self.AuthorizationFrame)
        self.AuthrroizationLabel.setGeometry(QtCore.QRect(0, 10, 301, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(97, 137, 47))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.AuthrroizationLabel.setPalette(palette)
        self.AuthrroizationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AuthrroizationLabel.setObjectName("AuthrroizationLabel")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.AuthorizationFrame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 301, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CityLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(229, 242, 255))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.CityLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.CityLabel.setFont(font)
        self.CityLabel.setObjectName("CityLabel")
        self.verticalLayout.addWidget(self.CityLabel)
        self.LoginField = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.LoginField.setObjectName("CityField")
        self.verticalLayout.addWidget(self.LoginField)
        self.nextButton = QtWidgets.QPushButton(self.AuthorizationFrame)
        self.nextButton.setGeometry(QtCore.QRect(0, 170, 299, 40))
        self.nextButton.setObjectName("registerButton")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "MemoryGame"))
        self.AuthrroizationLabel.setText(_translate("Widget", "Восстановление"))
        self.CityLabel.setText(_translate("Widget", "Введите ваш логин:"))
        self.nextButton.setText(_translate("Widget", "Далее"))

class EnteringAnswersUI(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(34, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        Widget.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        Widget.setFont(font)
        self.AuthorizationFrame = QtWidgets.QFrame(Widget)
        self.AuthorizationFrame.setEnabled(True)
        self.AuthorizationFrame.setGeometry(QtCore.QRect(250, 100, 301, 341))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(71, 75, 79))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        self.AuthorizationFrame.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(False)
        self.AuthorizationFrame.setFont(font)
        self.AuthorizationFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.AuthorizationFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.AuthorizationFrame.setLineWidth(300)
        self.AuthorizationFrame.setMidLineWidth(0)
        self.AuthorizationFrame.setObjectName("AuthorizationFrame")
        self.AuthrroizationLabel = QtWidgets.QLabel(self.AuthorizationFrame)
        self.AuthrroizationLabel.setGeometry(QtCore.QRect(0, 10, 301, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(97, 137, 47))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.AuthrroizationLabel.setPalette(palette)
        self.AuthrroizationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AuthrroizationLabel.setObjectName("AuthrroizationLabel")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.AuthorizationFrame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 301, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MotherLAbel = QtWidgets.QLabel(self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(229, 242, 255))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.MotherLAbel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.MotherLAbel.setFont(font)
        self.MotherLAbel.setObjectName("MotherLAbel")
        self.verticalLayout.addWidget(self.MotherLAbel)
        self.MotherField = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.MotherField.setObjectName("MotherField")
        self.verticalLayout.addWidget(self.MotherField)
        self.PetLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(229, 242, 255))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.PetLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.PetLabel.setFont(font)
        self.PetLabel.setObjectName("PetLabel")
        self.verticalLayout.addWidget(self.PetLabel)
        self.PetField = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.PetField.setObjectName("PetField")
        self.verticalLayout.addWidget(self.PetField)
        self.CityLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(229, 242, 255))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.CityLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.CityLabel.setFont(font)
        self.CityLabel.setObjectName("CityLabel")
        self.verticalLayout.addWidget(self.CityLabel)
        self.CityField = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.CityField.setObjectName("CityField")
        self.verticalLayout.addWidget(self.CityField)
        self.finishButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.finishButton.setObjectName("registerButton")
        self.verticalLayout.addWidget(self.finishButton)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "MemoryGame"))
        self.AuthrroizationLabel.setText(_translate("Widget", "Ответь на вопросы"))
        self.MotherLAbel.setText(_translate("Widget", "Девичья фамилия вашей матери:"))
        self.PetLabel.setText(_translate("Widget", "Имя первого домашнего питомца"))
        self.CityLabel.setText(_translate("Widget", "Город, где родился"))
        self.finishButton.setText(_translate("Widget", "Проверить"))

class ChangePasswordUI(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(34, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        Widget.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        Widget.setFont(font)
        self.AuthorizationFrame = QtWidgets.QFrame(Widget)
        self.AuthorizationFrame.setEnabled(True)
        self.AuthorizationFrame.setGeometry(QtCore.QRect(250, 100, 301, 221))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(71, 75, 79))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 137, 137))
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        self.AuthorizationFrame.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(False)
        self.AuthorizationFrame.setFont(font)
        self.AuthorizationFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.AuthorizationFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.AuthorizationFrame.setLineWidth(300)
        self.AuthorizationFrame.setMidLineWidth(0)
        self.AuthorizationFrame.setObjectName("AuthorizationFrame")
        self.AuthrroizationLabel = QtWidgets.QLabel(self.AuthorizationFrame)
        self.AuthrroizationLabel.setGeometry(QtCore.QRect(0, 10, 301, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(97, 137, 47))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.AuthrroizationLabel.setPalette(palette)
        self.AuthrroizationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AuthrroizationLabel.setObjectName("AuthrroizationLabel")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.AuthorizationFrame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 301, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PassLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(229, 242, 255))
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.PassLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.PassLabel.setFont(font)
        self.PassLabel.setObjectName("PassLabel")
        self.verticalLayout.addWidget(self.PassLabel)
        self.PassField = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.PassField.setObjectName("PassField")
        self.verticalLayout.addWidget(self.PassField)
        self.finishButton = QtWidgets.QPushButton(self.AuthorizationFrame)
        self.finishButton.setGeometry(QtCore.QRect(0, 170, 299, 40))
        self.finishButton.setObjectName("finishButton")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "MemoryGame"))
        self.AuthrroizationLabel.setText(_translate("Widget", "Восстановление"))
        self.PassLabel.setText(_translate("Widget", "Введите новый пароль:"))
        self.finishButton.setText(_translate("Widget", "Сменить пароль"))